apiVersion: v1
kind: Service
metadata:
  name: customerservice
spec:
# Uncomment type: NodePort & nodePort: <port> to expose mongo to internet.
  type: NodePort
  ports:
  - name: "8085"
    nodePort: 30085
    port: 8085
    targetPort: 8085
  selector:
    app: customer