apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerdeployment
spec:
  selector:
    matchLabels:
      app: customer
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: us.icr.io/pt1417/customerservice:1.0
        name: customer
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        
        volumeMounts:
        - name: customervolume
          mountPath: "/config"
      restartPolicy: Always
      volumes:
      - name: customervolume
        configMap:
          name: customercm
          items:
          - key: application.properties 
            path: application.properties